### ISSUE TITLE
IP removal request

### ISSUE THREAD

**Issue by kloevschall** [prbutler/EZProxy_IP_Blacklist#6]
Hi Paul,

One of our legitimate users was blocked by the blocklist due to the IP-address 185.126.109.167. 

The IP address belongs to a small Danish cable provider called HAS (Hjørring Antenneselskab).

Can you track why and when it was blocked and possibly remove it?

Best regards,
Kasper Løvschall

**Comment by prbutler** [comment]
Hi Kasper, 
As requested the IP was removed from the list during today's update. You submitted the address to me for inclusion on the list, along with many IPs, in an email on August 18, 2016. Feel free to email me directly if you need more info. 
Cheers, Paul
