### ISSUE TITLE
Confirming - Entry on line 23605 which affects 163,840 Hosts.

### ISSUE THREAD

**Issue by nestochan** [prbutler/EZProxy_IP_Blacklist#7]
Great work maintaining this list -- a huge thanks to you...

Just want to make sure that the following range added early December 2018 is correct...

The addition on line : `23605  RejectIP 219.151.128.0-219.153.255.255`

 Produces following EZProxy Log entry:

> WARNING: address range applies to `163840` hosts: 219.151.128.0-219.153.255.255

Just confirming it's  _"legit-ness"_ since it does affect 163,840 Hosts 

Thanks,
Ernesto
Northeastern University (Boston)

**Comment by prbutler** [comment]
Hi Ernesto,  

Thank you for bringing this to my attention. 

The  inclusion of the range on the list was legitimate. It was submitted by a library who had encountered issues from IPs within the range. I vaguely recall when I received the range sampling the IPs from the range and all seemed to geolocate to a similar region. 

That said, I forgot that older versions of EZproxy will trigger a "WARNING: address range applies to..." message in messages.txt for such a large range. This warning was removed from a later release of EZproxy (I am blanking on the exact release, towards the end of 2016 maybe?). As an EZproxy admin myself I don't want to cause other admins to panic with such a warning. 

So I have removed the range from the blacklist with today's update. Sites may still wish to block the range independent of the IP blacklist, which of course is their prerogative.  

Hope this clarifies things. 

Cheers, Paul
